openapi: 3.0.0
info:
  title: Task Management API
  description: API documentation for the Task Management & Reporting Dashboard
  version: 1.0.0
servers:
  - url: http://localhost:5000/api
    description: Local development server

paths:
  /auth/register:
    post:
      summary: Register a new user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                role:
                  type: string
                  enum: ["user", "admin"]
      responses:
        "201":
          description: User registered successfully
        "400":
          description: Validation error
          
  /auth/login:
    post:
      summary: Authenticate a user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: User authenticated successfully
        "401":
          description: Invalid credentials
          
  /tasks:
    post:
      summary: Create a new task
      tags:
        - Tasks
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
      responses:
        "201":
          description: Task created successfully
          
    get:
      summary: Get user-specific tasks
      tags:
        - Tasks
      security:
        - bearerAuth: []
      responses:
        "200":
          description: List of tasks assigned to the user

  /tasks/{taskId}:
    put:
      summary: Update a task
      tags:
        - Tasks
      security:
        - bearerAuth: []
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                status:
                  type: string
                  enum: ["pending", "in-progress", "completed"]
      responses:
        "200":
          description: Task updated successfully

    delete:
      summary: Delete a task
      tags:
        - Tasks
      security:
        - bearerAuth: []
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Task deleted successfully

  /reports/total-tasks:
    get:
      summary: Get total tasks created
      tags:
        - Reports
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Returns total number of tasks

  /reports/top-users:
    get:
      summary: Get top 3 most productive users
      tags:
        - Reports
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Returns top 3 users based on task count

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
